version: '3.2'
services:
  plugin:
    image: ghcr.io/arcalot/arcaflow-plugin-template
    build: .
    volumes:
      - source: ./example.yaml
        target: /config/example.yaml
        type: bind
