name: Carpenter
on:
  push:
    branches:
      - "**"
  release:
    types:
      - published
jobs:
  carpenter:
    uses: arcalot/arcaflow-reusable-workflows/.github/workflows/carpenter.yaml@main
    with:
      image_name: ${{ github.event.repository.name }}
      image_tag: 'latest'
      quay_img_exp: 'never'
      github_username: ${{ github.actor }}
      github_namespace: ${{ github.repository_owner }}
    secrets: inherit
