name: Arcaflow CI Workflow
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
  release:
    types:
      - published
jobs:
  act:
    uses: arcalot/arcaflow-container-toolkit/.github/workflows/reusable_workflow.yaml@4e4973a207613100bbc46de6f9e2a05a9311a15a # main
    with:
      image_name: ${{ github.event.repository.name }}
      image_tag: 'latest'
      multi_arch: true
    secrets:
      QUAY_NAMESPACE: ${{ secrets.QUAY_NAMESPACE }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}

  docsgen:
    needs: act
    uses: arcalot/arcaflow-docsgen/.github/workflows/reusable_workflow.yaml@a3fab7472358b6815ddd56c90ceffae314e7f347 # main
    permissions:
      contents: write
      pull-requests: write
    with:
      plugin_path: "arcaflow_plugin_metadata/metadata_plugin.py"
    